runtime: python310
service: trendalyzer
entrypoint: gunicorn -b :$PORT trendtracker.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: "trendtracker.settings"
  DJANGO_SECRET_KEY: "your-production-secret"
  DEBUG: "False"
